version: "3.7"
services:
  cluster:
    container_name: gcdcluster
    environment:
      INFLUXDB: "http://192.168.2.10:8086"
      GCD_CLUSTER_LISTENING_PORT: 5432
      GCD_CLUSTER_NODES: "[{'MachineName':'192.168.2.10','Port':9090}]"
    build:
      context: ../
      dockerfile: GrandCentralDispatch.Cluster/Dockerfile
    image: gcd/cluster:v1
    ports:
      - "5432:5432"
    networks:
      - gcd
  grafana:
    build: './grafana'
    container_name: grafana
    restart: always
    image: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - gcd
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb
    networks:
      - gcd
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: admin
    networks:
      - gcd
  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.1
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - gcd
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - gcd
configs:
  elastic_config:
    file: ./elk/elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./elk/logstash/config/logstash.yml
  logstash_pipeline:
    file: ./elk/logstash/pipeline/logstash.conf
  kibana_config:
    file: ./elk/kibana/config/kibana.yml
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
networks:
  gcd:
    driver: overlay