{
 "title": "Nodes Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Items Processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_machine_name",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__node_items_processed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Buffer size" }
   ],
   "targets": [
    {
     "alias": "Buffer size (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__node_buffer_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "Throughput (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__node_throughput",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Items Evicted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops", "label": "Items evicted" }
   ],
   "targets": [
    {
     "alias": "Items evicted (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__node_items_evicted",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}