{
 "title": "Nodes Health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Monitor Lock Contention Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Monitor Lock Contention Count" }
   ],
   "targets": [
    {
     "alias": "Monitor Lock Contention Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "node_id" ], "type": "tag" },
      { "params": [ "machine_name" ], "type": "tag" }
     ],
     "measurement": "node__monitor_lock_contention_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadPool Completed Work Item Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    {
     "format": "short",
     "label": "ThreadPool Completed Work Item Count"
    }
   ],
   "targets": [
    {
     "alias": "ThreadPool Completed Work Item Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__threadpool_completed_work_item_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadPool Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ThreadPool Queue Length" }
   ],
   "targets": [
    {
     "alias": "ThreadPool Queue Length (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__threadpool_queue_length",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "alias": "CPU Usage (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__cpu_usage",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes", "label": "GC Heap Size" }
   ],
   "targets": [
    {
     "alias": "GC Heap Size (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gc_heap_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Allocation Rate" }
   ],
   "targets": [
    {
     "alias": "Allocation Rate (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__allocation_rate",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "LOH Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes", "label": "LOH Size" }
   ],
   "targets": [
    {
     "alias": "LOH Size (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__loh_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 0 Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes", "label": "Gen 0 Size" }
   ],
   "targets": [
    {
     "alias": "Gen 0 Size (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gen_0_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 1 Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes", "label": "Gen 1 Size" }
   ],
   "targets": [
    {
     "alias": "Gen 1 Size (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gen_1_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 2 Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes", "label": "Gen 2 Size" }
   ],
   "targets": [
    {
     "alias": "Gen 2 Size (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gen_2_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 0 GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Gen 0 GC Count" }
   ],
   "targets": [
    {
     "alias": "Gen 0 GC Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gen_0_gc_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 1 GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Gen 1 GC Count" }
   ],
   "targets": [
    {
     "alias": "Gen 1 GC Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gen_1_gc_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 2 GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Gen 2 GC Count" }
   ],
   "targets": [
    {
     "alias": "Gen 2 GC Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__gen_2_gc_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Time in GC since last GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent", "label": "% Time in GC since last GC" }
   ],
   "targets": [
    {
     "alias": "% Time in GC since last GC (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__%_time_in_gc_since_last_gc",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decmbytes", "label": "Working Set" }
   ],
   "targets": [
    {
     "alias": "Working Set (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__working_set",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadPool Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "ThreadPool Thread Count" }
   ],
   "targets": [
    {
     "alias": "ThreadPool Thread Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "node_id" ], "type": "tag" },
      { "params": [ "machine_name" ], "type": "tag" }
     ],
     "measurement": "node__threadpool_thread_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Assemblies Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Number of Assemblies Loaded" }
   ],
   "targets": [
    {
     "alias": "Number of Assemblies Loaded (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__number_of_assemblies_loaded",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Active Timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Number of Active Timers" }
   ],
   "targets": [
    {
     "alias": "Number of Active Timers (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__number_of_active_timers",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exception Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Exception Count" }
   ],
   "targets": [
    {
     "alias": "Exception Count (Node name: $tag_machine_name - Node guid: $tag_node_id)",
     "groupBy": [
      { "params": [ "machine_name" ], "type": "tag" },
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "node__exception_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}