{
 "title": "App Metrics - Web Monitoring - InfluxDB",
 "description": "Dashboard to visualize metrics captured by App Metrics ASP.NET Core Middleware, tested with App.Metrics.Reporting.InfluxDB 2.0.0",
 "tags": [ "influxdb" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "influxdb" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"env\""
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SHOW TAG VALUES WITH KEY = \"app\""
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES WITH KEY = \"server\""
   },
   { "name": "writefrequency", "label": "Write Frequency", "query": "1s,2s,5s,10s,1m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "rpm",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "apdex" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__apdex",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__one_minute_error_percentage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_http_status_code",
     "groupBy": [
      { "params": [ "http_status_code" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncaught Exceptions Thrown",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 24 },
   "targets": [
    {
     "alias": "$tag_exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "exception" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__exceptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Throughput / Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time / Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Times / Endpoint",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Error Request Percentage / Endpoint",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "$tag_route",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__one_minute_error_percentage_rate_per_endpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncaught Exceptions Thrown / Endpoint",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "alias": "$tag_route [$tag_exception]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "exception" ], "type": "tag" }
     ],
     "measurement": "application.httprequests__exceptions",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "PUT & POST Request Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "POST Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__post_size",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "median" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "PUT Request Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__put_size",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "median" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Check Pulse",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_health_check_name",
     "groupBy": [
      { "params": [ "health_check_name" ], "type": "tag" }
     ],
     "measurement": "application.health__results",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Check Results",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "alias": "$tag_health_check_name",
     "groupBy": [
      { "params": [ "health_check_name" ], "type": "tag" }
     ],
     "measurement": "application.health__results",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}