{
 "title": "Cluster Health",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Operations/s" }
   ],
   "targets": [
    {
     "alias": "Cluster Throughput",
     "measurement": "application__cluster_throughput",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monitor Lock Contention Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Monitor Lock Contention Count" }
   ],
   "targets": [
    {
     "alias": "Monitor Lock Contention Count",
     "measurement": "cluster__monitor_lock_contention_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadPool Completed Work Item Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    {
     "format": "short",
     "label": "ThreadPool Completed Work Item Count"
    }
   ],
   "targets": [
    {
     "alias": "ThreadPool Completed Work Item Count",
     "measurement": "cluster__threadpool_completed_work_item_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadPool Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "ThreadPool Queue Length" }
   ],
   "targets": [
    {
     "alias": "ThreadPool Queue Length",
     "measurement": "cluster__threadpool_queue_length",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "CPU Usage" }
   ],
   "targets": [
    {
     "alias": "CPU Usage",
     "measurement": "cluster__cpu_usage",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Heap Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decmbytes", "label": "GC Heap Size" }
   ],
   "targets": [
    {
     "alias": "GC Heap Size",
     "measurement": "cluster__gc_heap_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Allocation Rate" }
   ],
   "targets": [
    {
     "alias": "Allocation Rate",
     "measurement": "cluster__allocation_rate",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "LOH Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes", "label": "LOH Size" }
   ],
   "targets": [
    {
     "alias": "LOH Size",
     "measurement": "cluster__loh_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 0 Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes", "label": "Gen 0 Size" }
   ],
   "targets": [
    {
     "alias": "Gen 0 Size",
     "measurement": "cluster__gen_0_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 1 Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes", "label": "Gen 1 Size" }
   ],
   "targets": [
    {
     "alias": "Gen 1 Size",
     "measurement": "cluster__gen_1_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 2 Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes", "label": "Gen 2 Size" }
   ],
   "targets": [
    {
     "alias": "Gen 2 Size",
     "measurement": "cluster__gen_2_size",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 0 GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Gen 0 GC Count" }
   ],
   "targets": [
    {
     "alias": "Gen 0 GC Count",
     "measurement": "cluster__gen_0_gc_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 1 GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Gen 1 GC Count" }
   ],
   "targets": [
    {
     "alias": "Gen 1 GC Count",
     "measurement": "cluster__gen_1_gc_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gen 2 GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Gen 2 GC Count" }
   ],
   "targets": [
    {
     "alias": "Gen 2 GC Count",
     "measurement": "cluster__gen_2_gc_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Time in GC since last GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "percent", "label": "% Time in GC since last GC" }
   ],
   "targets": [
    {
     "alias": "% Time in GC since last GC",
     "measurement": "cluster__%_time_in_gc_since_last_gc",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decmbytes", "label": "Working Set" }
   ],
   "targets": [
    {
     "alias": "Working Set",
     "measurement": "cluster__working_set",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ThreadPool Thread Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "ThreadPool Thread Count" }
   ],
   "targets": [
    {
     "alias": "ThreadPool Thread Count",
     "measurement": "cluster__threadpool_thread_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Assemblies Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "Number of Assemblies Loaded" }
   ],
   "targets": [
    {
     "alias": "Number of Assemblies Loaded",
     "measurement": "cluster__number_of_assemblies_loaded",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Active Timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "Number of Active Timers" }
   ],
   "targets": [
    {
     "alias": "Number of Active Timers",
     "measurement": "cluster__number_of_active_timers",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exception Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Exception Count" }
   ],
   "targets": [
    {
     "alias": "Exception Count",
     "measurement": "cluster__exception_count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}